---
title: "Jeff"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
data <- read.csv(here("data", "data_export_20240424.csv"), sep = ";")
```

```{r}
consumptiondata <- read.csv(here("data", "energyconsumption.csv"), sep = ";")
```

```{r}
temperature <- read.csv(here("data", "temperature.csv"), sep = ";")
```

## Pivot Months for the temperature dataset

```{r}
temperature <- temperature %>% 
  pivot_longer(c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'),
  names_to = "Month",
  values_to = "Temperature")
```

## Convert Month into Date

```{r}
data$Month <- as.Date(data$Month, format = "%d.%m.%y")
```

## Replace "Not Available" with NA, then 0

```{r}
data$Solar_Energy_Production <- replace(data$Solar_Energy_Production, data$Solar_Energy_Production == "Not Available", 0)
data$Solar_Energy_Production %>% as.numeric(data$Solar_Energy_Production)
typeof(data$Solar_Energy_Production)

data$Solar_Energy_Production <- ifelse(data$Solar_Energy_Production == "Not Available", 0, data$Solar_Energy_Production)
data$Wind_Energy_Production <- ifelse(data$Wind_Energy_Production == "Not Available", 0, data$Wind_Energy_Production)

data$Solar_Energy_Production <- as.numeric(data$Solar_Energy_Production)
data$Wind_Energy_Production <- as.numeric(data$Wind_Energy_Production)
```

## Plot Data

```{r}
# Coal Production
library(ggplot2)
ggplot(data, aes(x = Month, y = Coal_Production)) + 
  geom_line() + 
  labs(title = "Time Series Plot", x = "Date", y = "Value")

summary(data$Coal_Production)

# Natural Gas Dry Production
library(ggplot2)
ggplot(data, aes(x = Month, y = Natural_Gas_Dry_Production)) + 
  geom_line() + 
  labs(title = "Time Series Plot", x = "Date", y = "Value")

# Crude Oil Production
library(ggplot2)
ggplot(data, aes(x = Month, y = Crude_Oil_Production)) + 
  geom_line() + 
  labs(title = "Time Series Plot", x = "Date", y = "Value")

# Natural Gas Plant Liquids Production
library(ggplot2)
ggplot(data, aes(x = Month, y = Natural_Gas_Plant_Liquids_Production)) + 
  geom_line() + 
  labs(title = "Time Series Plot", x = "Date", y = "Value")

# Total Fossil Fuels Production
library(ggplot2)
ggplot(data, aes(x = Month, y = Total_Fossil_Fuels_Production)) + 
  geom_line() + 
  labs(title = "Time Series Plot", x = "Date", y = "Value")

#Nuclear Electric Power Production
library(ggplot2)
ggplot(data, aes(x = Month, y = Nuclear_Electric_Power_Production)) + 
  geom_line() + 
  labs(title = "Time Series Plot", x = "Date", y = "Value")

# Hydroelectric Power Production
library(ggplot2)
ggplot(data, aes(x = Month, y = Hydroelectric_Power_Production)) + 
  geom_line() + 
  labs(title = "Time Series Plot", x = "Date", y = "Value")

# Geothermal Energy Production
library(ggplot2)
ggplot(data, aes(x = Month, y = Geothermal_Energy_Production)) + 
  geom_line() + 
  labs(title = "Time Series Plot", x = "Date", y = "Value")

# Solar Energy Production
library(ggplot2)
ggplot(data, aes(x = Month, y = Solar_Energy_Production)) + 
  geom_line() + 
  labs(title = "Time Series Plot", x = "Date", y = "Value")

# Wind Energy Production
library(ggplot2)
ggplot(data, aes(x = Month, y = Wind_Energy_Production)) + 
  geom_line() + 
  labs(title = "Time Series Plot", x = "Date", y = "Value")

# Biomass Energy Production
library(ggplot2)
ggplot(data, aes(x = Month, y = Biomass_Energy_Production)) + 
  geom_line() + 
  labs(title = "Time Series Plot", x = "Date", y = "Value")

# Total Renewable Energy Production
library(ggplot2)
ggplot(data, aes(x = Month, y = Total_Renewable_Energy_Production)) + 
  geom_line() + 
  labs(title = "Time Series Plot", x = "Date", y = "Value")

# Total Primary Energy Production
library(ggplot2)
ggplot(data, aes(x = Month, y = Total_Primary_Energy_Production)) + 
  geom_line() + 
  labs(title = "Time Series Plot", x = "Date", y = "Value")
```

